version: '3'
volumes:
  prometheus: {}

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongodb_exporter:
    image: percona/mongodb_exporter:0.20
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongodb_exporter:password@mongo:27017
    command:
      - '--mongodb.collstats-colls=test.posts,test.users'
      - '--mongodb.indexstats-colls=test.posts,test.users'
      - '--compatible-mode'
    ports:
      - 9216:9216
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
